### ISSUE TITLE
[bug] not all icons are displayed

### ISSUE THREAD

**Issue by tumuyan** [Macro-Deck-org/Macro-Deck-Web-Client#5]
Some icons may be refreshed each time the page is refreshed,
Sometimes the icon of the button will be refreshed when the button is clicked.
But always not all icons are displayed.

![image](https://user-images.githubusercontent.com/3126801/184145224-d7143d7d-6fae-4db3-ba75-3600c32ec61a.png)

**Comment by SuchByte** [comment]
Try to clear the cache of your web browser or try another browser and please tell me if it is fixed then.

**Comment by tumuyan** [comment]
I re-installed opera browser on my Android device last weekend, still have the same problem.
I observe the dom in edge and click a button, sometime the button change and fresh the base64 encode image, sometime it not get the base64 encode image
